language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - "pip install -r requirements.txt"
  - "pip install -e ."
script: pytest && flake8 && mypy -p aiohttp_spyne && black --check aiohttp_spyne
notifications:
  email: false
