language: python
python:
  - "pypy3"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - "pip install -r requirements.txt"
  - "pip install -e ."
script: pytest tests/main_tests.py
notifications:
  email: false
