language: python
python:
  - "3.8"
  - "3.9"
# Python 3.10 testing is disabled for now, since only old 3.10-dev (incompatible) is available.
#  - "3.10"
install:
  - "pip install -r requirements.txt"
  - "pip install -e ."
script: pytest && flake8 && mypy -p aiohttp_spyne && black --check aiohttp_spyne
notifications:
  email: false
